apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-event-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      triggerRef:
        name: my-github-trigger
