apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      binding:
        ref: git-trigger-binding
      template:
        ref: pipeline-trigger-template