apiVersion: v1
kind: Service
metadata:
  name: el-git
  namespace: tekton-pipelines
spec:
  selector:
    eventlistener: git-event-listener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
